#!/usr/bin/env bash
# Bring up the local OpenShell gateway for the ODIS contract harness OpenShell-gated demo.
#
# Repo-free: pulls the PUBLISHED gateway image (no OpenShell source checkout). The only
# prerequisites are Docker + the `openshell` CLI (mise: `pipx:openshell`) + openssl.
#
#   bash setup.sh
#   mise run openshell-connect   # register/select; status -> Connected
set -euo pipefail
cd "$(dirname "$0")"

# The Docker compute driver mints supervisor<->gateway JWTs and requires an ed25519
# signing key. jwt-signing.pem is a PRIVATE key — created under umask 077 (private
# from the first byte, no chmod window), gitignored, never committed. Each artifact
# is derived independently so an interrupted setup is recoverable on re-run.
umask 077
if [ ! -f jwt-signing.pem ]; then
  echo "[setup] generating gateway JWT signing material (ed25519)..."
  openssl genpkey -algorithm ed25519 -out jwt-signing.pem
fi
chmod 600 jwt-signing.pem
[ -f jwt-public.pem ] || openssl pkey -in jwt-signing.pem -pubout -out jwt-public.pem
[ -f jwt-kid ] || openssl rand -hex 8 > jwt-kid

# Port 8080 is NON-NEGOTIABLE: the sandbox->gateway callback dials
# host.openshell.internal:8080 through the host-published mapping. If another
# service owns 8080, sandbox provisioning strands in a restart loop mid-demo —
# fail fast here instead (unless the listener is our own already-running gateway).
if ! docker compose ps --status running 2>/dev/null | grep -q gateway; then
  if curl -s -o /dev/null --max-time 2 "http://localhost:8080/"; then
    echo "[setup] FAIL: another service already listens on port 8080; the sandbox->gateway"
    echo "        callback path requires it. Free port 8080 and re-run."
    exit 1
  fi
fi

# Sandboxes run on the `openshell-docker` network, and the driver resolves
# host.openshell.internal to THAT network's gateway address — not to loopback. The
# published mapping must include it or every sandbox strands on "Policy fetch failed".
# gateway.toml binds 127.0.0.1 inside the container, so the address is supplied here.
# The network is created up front rather than on first sandbox launch, so its address is
# known before compose starts.
docker network inspect openshell-docker >/dev/null 2>&1 \
  || docker network create openshell-docker >/dev/null
sandbox_net_gw="$(docker network inspect openshell-docker \
  --format '{{(index .IPAM.Config 0).Gateway}}')"
if [ -z "$sandbox_net_gw" ]; then
  echo "[setup] FAIL: could not read the openshell-docker network gateway address"
  exit 1
fi
cat > docker-compose.override.yml <<EOF
# Generated by setup.sh. Publishes the control plane on the sandbox network's gateway
# address so sandbox->gateway callbacks resolve. Regenerated on every run; not committed.
services:
  gateway:
    ports:
      - "127.0.0.1:8080:8080"
      - "${sandbox_net_gw}:8080:8080"
EOF
echo "[setup] sandbox callback address: ${sandbox_net_gw}:8080"

echo "[setup] starting the OpenShell gateway (docker compose up -d)..."
docker compose up -d

echo "[setup] waiting for the gateway to accept connections on :8080..."
ready=""
for _ in $(seq 1 60); do
  if curl -s -o /dev/null "http://localhost:8080/"; then
    ready=1
    break
  fi
  sleep 1
done
if [ -z "$ready" ]; then
  echo "[setup] FAIL: gateway not reachable on http://localhost:8080 after 60s (see: docker compose logs gateway)"
  exit 1
fi

echo "[setup] gateway up on http://localhost:8080"
echo "[setup] next: mise run openshell-connect"
