"""RuntimeContextFactory — trusted-identity production for the Router.

The Router must build the `RuntimeContext` (ODIS Delegation Record) from
trusted Passport/Sponsor providers, never from agent-supplied input. This
factory reuses the kept identity providers (`substrate/identity.py` +
`fixtures.py`) and is the Router's replacement for the SubstrateStub
orchestrator's `_build_runtime_context` (the orchestrator itself is bound to
the deleted EnforcementAdapter).

Security property: `sponsor` always comes from the sponsor provider. The
`agent_id` is agent-claimed but only becomes a runtime identity because the
workload-identity provider issues a credential for it — the provider is the
gate, not the agent.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING

from odis_harness.contracts import RuntimeContext, now_iso

if TYPE_CHECKING:
    from odis_harness.substrate.identity import (
        SponsorIdentityProvider,
        WorkloadIdentityProvider,
    )

#: The `agent.type` recorded in the RuntimeContext. Reflects that the harness
#: uses the fixture workload-identity provider; a real Passport implementation
#: (SPIFFE/SAT/…) would surface its own type.
_AGENT_TYPE = "fixture_workload_identity"


@dataclass(frozen=True, kw_only=True, slots=True)
class RuntimeContextFactory:
    """Builds a trusted `RuntimeContext` from Passport + Sponsor providers."""

    workload_identity: WorkloadIdentityProvider
    sponsor_provider: SponsorIdentityProvider

    def build(  # noqa: PLR0913 - all kw-only; each names a distinct RuntimeContext field
        self,
        *,
        agent_id: str,
        resource_family: str,
        tool: str,
        policy_digest: str,
        correlation_id: str,
        task_intent: str = "",
    ) -> RuntimeContext:
        """Produce a `RuntimeContext` for a single forward.

        `resource_family` is set explicitly from the bundle's family name — it
        is NOT inferred from the tool name. `correlation_id` is generated by
        the Router and threaded through every event for this action.
        """
        sponsor = self.sponsor_provider.current_sponsor()
        credential = self.workload_identity.issue(sponsor_id=sponsor.id, agent_id=agent_id)
        return RuntimeContext(
            correlation_id=correlation_id,
            sponsor={"id": sponsor.id, "type": sponsor.type},
            agent={"id": credential.agent_id, "type": _AGENT_TYPE},
            task_intent=task_intent or f"invoke {resource_family}.{tool}",
            target_resource={"resource_family": resource_family},
            issued_at=now_iso(),
            policy_digest=policy_digest,
        )


__all__ = ["RuntimeContextFactory"]
