"""RuntimeContextFactory — trusted-identity production for the Router.

Builds the `RuntimeContext` from the injected Passport and originating-principal
providers, never from agent-supplied input.

`RuntimeContext` is **not** an ODIS Delegation Record: §6.3 requires fifteen mandatory
fields including `originating_authorization_ref`, `attenuation_profile_ref` and integrity
protection, and this carries five. It is the harness's own per-call identity envelope.

Security property: `originating_principal` always comes from the provider. The `agent_id`
is agent-claimed but only becomes a runtime identity because the workload-identity
provider issues a credential for it — the provider is the gate, not the agent.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING

from odis_harness.contracts import RuntimeContext, now_iso

if TYPE_CHECKING:
    from odis_harness.bundle import Bundle
    from odis_harness.substrate.identity import (
        OriginatingPrincipalProvider,
        WorkloadIdentityProvider,
    )

#: The `agent.type` recorded in the RuntimeContext. Reflects that the harness
#: uses the fixture workload-identity provider; a real Passport implementation
#: (SPIFFE/SAT/…) would surface its own type.
_AGENT_TYPE = "fixture_workload_identity"


@dataclass(frozen=True, kw_only=True, slots=True)
class RuntimeContextFactory:
    """Builds a trusted `RuntimeContext` from Passport + originating-principal providers."""

    workload_identity: WorkloadIdentityProvider
    principal_provider: OriginatingPrincipalProvider

    def build(  # noqa: PLR0913 - all kw-only; each names a distinct RuntimeContext field
        self,
        *,
        agent_id: str,
        resource_family: str,
        tool: str,
        bundle: Bundle,
        correlation_id: str,
        task_intent: str = "",
    ) -> RuntimeContext:
        """Produce a `RuntimeContext` for a single forward.

        `resource_family` is set explicitly from the bundle's family name — it
        is NOT inferred from the tool name. `correlation_id` is generated by
        the Router and threaded through every event for this action.
        """
        principal = self.principal_provider.current_principal()
        credential = self.workload_identity.issue(principal_id=principal.id, agent_id=agent_id)
        return RuntimeContext(
            correlation_id=correlation_id,
            originating_principal={"id": principal.id, "type": principal.type},
            agent={"id": credential.agent_id, "type": _AGENT_TYPE},
            task_intent=task_intent or f"invoke {resource_family}.{tool}",
            target_resource={"resource_family": resource_family},
            issued_at=now_iso(),
            policy_digest=bundle.policy_digest,
            bundle_id=bundle.bundle_id,
            bundle_version=bundle.bundle_version,
            trust_root_id=bundle.trust_root_id,
        )


__all__ = ["RuntimeContextFactory"]
