"""RuntimeContextFactory — trusted-identity production for the Router.

Builds the `RuntimeContext` from the injected Passport and originating-principal
providers, never from agent-supplied input.

`RuntimeContext` is **not** an ODIS Delegation Record: §6.3 requires fifteen mandatory
fields including `originating_authorization_ref`, `attenuation_profile_ref` and integrity
protection, and this carries five. It is the harness's own per-call identity envelope.

Security property: neither identity comes from the tool-call payload.
`originating_principal` always comes from its provider. `agent_id` comes from the
`CallerIdentity` the transport resolved — the subject of a validated credential where one
was presented, and the unauthenticated fallback otherwise, with `agent.type` recording
which. The workload-identity provider is still called and can refuse, so it remains a
gate; it is not the *source* of the id, because a provider that substituted one would
have its substitution recorded as though it had arrived on the caller's credential.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING

from odis_harness.contracts import RuntimeContext, now_iso

if TYPE_CHECKING:
    from odis_harness.bundle import Bundle
    from odis_harness.substrate.identity import (
        OriginatingPrincipalProvider,
        WorkloadIdentityProvider,
    )

#: The `agent.type` for an identity the Router did not verify — the in-process paths.
#: Kept distinct from `VERIFIED_AGENT_TYPE` so a policy or an audit reader can tell a
#: fixture identity from one that arrived on a validated credential.
UNVERIFIED_AGENT_TYPE = "fixture_workload_identity"

#: The `agent.type` for an id taken from a credential the transport verified. Names the
#: *strength* of the identity, not the scheme: `token_verifier` is a public seam, so the
#: handler cannot know whether a SPIFFE JWT-SVID or some other bearer was checked, and
#: recording a specific scheme would assert something it did not observe.
VERIFIED_AGENT_TYPE = "verified_bearer"


@dataclass(frozen=True, kw_only=True, slots=True)
class CallerIdentity:
    """Who the Router believes it is acting for, and on what evidence.

    One object rather than two parallel arguments because the pair must move together:
    an `agent_id` lifted from a verified credential recorded under the *unverified* type
    would misreport the strength of the identity in every audit event it appears in.
    """

    agent_id: str
    #: How `agent_id` was established — one of the two constants above.
    agent_type: str = UNVERIFIED_AGENT_TYPE

    @classmethod
    def verified(cls, agent_id: str) -> CallerIdentity:
        """An id taken from a credential the transport validated."""
        return cls(agent_id=agent_id, agent_type=VERIFIED_AGENT_TYPE)


@dataclass(frozen=True, kw_only=True, slots=True)
class RuntimeContextFactory:
    """Builds a trusted `RuntimeContext` from Passport + originating-principal providers."""

    workload_identity: WorkloadIdentityProvider
    principal_provider: OriginatingPrincipalProvider

    def build(  # noqa: PLR0913 - all kw-only; each names a distinct RuntimeContext field
        self,
        *,
        caller: CallerIdentity,
        resource_family: str,
        tool: str,
        bundle: Bundle,
        correlation_id: str,
        task_intent: str = "",
    ) -> RuntimeContext:
        """Produce a `RuntimeContext` for a single forward.

        `resource_family` is set explicitly from the bundle's family name — it
        is NOT inferred from the tool name. `correlation_id` is generated by
        the Router and threaded through every event for this action.
        """
        principal = self.principal_provider.current_principal()
        # The credential is still minted: the workload-identity provider is a gate that
        # can refuse. But the id recorded is `caller`'s, not the credential's — pairing a
        # provider-substituted id with `caller.agent_type` would report a value the Router
        # never received as having come off a verified bearer.
        self.workload_identity.issue(principal_id=principal.id, agent_id=caller.agent_id)
        return RuntimeContext(
            correlation_id=correlation_id,
            originating_principal={"id": principal.id, "type": principal.type},
            agent={"id": caller.agent_id, "type": caller.agent_type},
            task_intent=task_intent or f"invoke {resource_family}.{tool}",
            target_resource={"resource_family": resource_family},
            issued_at=now_iso(),
            policy_digest=bundle.policy_digest,
            bundle_id=bundle.bundle_id,
            bundle_version=bundle.bundle_version,
            trust_root_id=bundle.trust_root_id,
        )


__all__ = [
    "UNVERIFIED_AGENT_TYPE",
    "VERIFIED_AGENT_TYPE",
    "CallerIdentity",
    "RuntimeContextFactory",
]
